apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-test-app
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
      - name: flask-test-app
        image: gcr.io/k8s-minikube/kicbase:v0.0.40
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
