apiVersion: v1
kind: Service
metadata:
  name: flask-test-service
spec:
  selector:
    app: flask-test-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-test-app
  template:
    metadata:
      labels:
        app: flask-test-app
    spec:
      containers:
      - name: flask-test-app
        image: gcr.io/k8s-minikube/kicbase:v0.0.40
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "0.5"   # Request 0.5 CPU cores
            memory: "256Mi"  # Request 256 MiB of memory
          limits:
            cpu: "4"  # Limit to 4 CPU core
            memory: "512Mi"  # Limit to 512 MiB of memory
